version: '3.8'
services:
  gateway:
    build: ./nginx
    ports:
      - "3000:8080" # 把宿主机 3000 端口映射到 nginx 容器的 8080
    environment:
      # 默认指向名为 `genshin-backend` 的容器
      - VITE_API_URL=${VITE_API_URL:-http://genshin-backend:8080}
    networks:
      - moelink_net

networks:
  moelink_net:
    external: true
